version: '3'

services:
  mysqlsrv:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "pass1234"
      MYSQL_DATABASE: "php-practitioner"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge